/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.skyhigh.storeapi.controller;

import com.skyhigh.storeapi.model.dto.BranchDto;
import com.skyhigh.storeapi.model.dto.BranchResponseDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-05-17T22:49:14.789018+05:30[Asia/Colombo]")
@Validated
@Tag(name = "branch", description = "Access to Branch")
public interface BranchApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /branch : Add a new Branch to the app
     * Add a new Store to the app
     *
     * @param branchDto Create a new Branch to the app (required)
     * @return Successful operation (status code 200)
     *         or Invalid input (status code 405)
     */
    @Operation(
            operationId = "addBranch",
            summary = "Add a new Branch to the app",
            tags = { "branch" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BranchResponseDto.class)),
                            @Content(mediaType = "application/xml", schema = @Schema(implementation = BranchResponseDto.class))
                    }),
                    @ApiResponse(responseCode = "405", description = "Invalid input")
            },
            security = {
                    @SecurityRequirement(name = "bearerAuth")
            }
    )
    @PreAuthorize("hasRole('store-admin')")
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/branch",
            produces = { "application/json", "application/xml" },
            consumes = { "application/json", "application/xml", "application/x-www-form-urlencoded" }
    )
    default ResponseEntity<BranchResponseDto> addBranch(
            @Parameter(name = "BranchDto", description = "Create a new Branch to the app", required = true) @Valid @RequestBody BranchDto branchDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"branchId\" : 10, \"photoUrl\" : \"photoUrl\", \"address\" : { \"zip\" : \"94301\", \"country\" : \"Canada\", \"addresLine1\" : \"437 Lytton\", \"addresLine2\" : \"437 Lytton\", \"city\" : \"Palo Alto\", \"state\" : \"CA\", \"addressId\" : 10 }, \"branchName\" : \"Branch Toronto\", \"store\" : { \"photoUrl\" : \"photoUrl\", \"address\" : { \"zip\" : \"94301\", \"country\" : \"Canada\", \"addresLine1\" : \"437 Lytton\", \"addresLine2\" : \"437 Lytton\", \"city\" : \"Palo Alto\", \"state\" : \"CA\", \"addressId\" : 10 }, \"storeName\" : \"Auto Range, MagCity\", \"storeId\" : 10, \"status\" : \"ACTIVE\" }, \"status\" : \"ACTIVE\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/xml"))) {
                    String exampleString = "<BranchResponseDto> <branchId>10</branchId> <branchName>Branch Toronto</branchName> <photoUrl>aeiou</photoUrl> <status>aeiou</status> </BranchResponseDto>";
                    ApiUtil.setExampleResponse(request, "application/xml", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /branch/{branchId} : Deletes a Branch
     * delete a Branch
     *
     * @param branchId Branch id to delete (required)
     * @param apiKey  (optional)
     * @return Invalid Store value (status code 400)
     */
    @Operation(
            operationId = "deleteBranch",
            summary = "Deletes a Branch",
            tags = { "branch" },
            responses = {
                    @ApiResponse(responseCode = "400", description = "Invalid Store value")
            },
            security = {
                    @SecurityRequirement(name = "bearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/branch/{branchId}"
    )
    default ResponseEntity<Void> deleteBranch(
            @Parameter(name = "branchId", description = "Branch id to delete", required = true) @PathVariable("branchId") Long branchId,
            @Parameter(name = "api_key", description = "") @RequestHeader(value = "api_key", required = false) String apiKey
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /branch/findByStatus : Finds Branch by status
     * Multiple status values can be provided with comma separated strings
     *
     * @param status Status values that need to be considered for filter (optional, default to ACTIVE)
     * @return successful operation (status code 200)
     *         or Invalid status value (status code 400)
     */
    @Operation(
            operationId = "findBranchByStatus",
            summary = "Finds Branch by status",
            tags = { "branch" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "successful operation", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BranchResponseDto.class)),
                            @Content(mediaType = "application/xml", schema = @Schema(implementation = BranchResponseDto.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid status value")
            },
            security = {
                    @SecurityRequirement(name = "bearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/branch/findByStatus",
            produces = { "application/json", "application/xml" }
    )
    default ResponseEntity<List<BranchResponseDto>> findBranchByStatus(
            @Parameter(name = "status", description = "Status values that need to be considered for filter") @Valid @RequestParam(value = "status", required = false, defaultValue = "ACTIVE") String status
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"branchId\" : 10, \"photoUrl\" : \"photoUrl\", \"address\" : { \"zip\" : \"94301\", \"country\" : \"Canada\", \"addresLine1\" : \"437 Lytton\", \"addresLine2\" : \"437 Lytton\", \"city\" : \"Palo Alto\", \"state\" : \"CA\", \"addressId\" : 10 }, \"branchName\" : \"Branch Toronto\", \"store\" : { \"photoUrl\" : \"photoUrl\", \"address\" : { \"zip\" : \"94301\", \"country\" : \"Canada\", \"addresLine1\" : \"437 Lytton\", \"addresLine2\" : \"437 Lytton\", \"city\" : \"Palo Alto\", \"state\" : \"CA\", \"addressId\" : 10 }, \"storeName\" : \"Auto Range, MagCity\", \"storeId\" : 10, \"status\" : \"ACTIVE\" }, \"status\" : \"ACTIVE\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/xml"))) {
                    String exampleString = "<BranchResponseDto> <branchId>10</branchId> <branchName>Branch Toronto</branchName> <photoUrl>aeiou</photoUrl> <status>aeiou</status> </BranchResponseDto>";
                    ApiUtil.setExampleResponse(request, "application/xml", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /branch/{branchId} : Find Branch by ID
     * Returns a single Branch
     *
     * @param branchId ID of Branch to return (required)
     * @return successful operation (status code 200)
     *         or Invalid ID supplied (status code 400)
     *         or Branch not found (status code 404)
     */
    @Operation(
            operationId = "getBranchById",
            summary = "Find Branch by ID",
            tags = { "branch" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "successful operation", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BranchResponseDto.class)),
                            @Content(mediaType = "application/xml", schema = @Schema(implementation = BranchResponseDto.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
                    @ApiResponse(responseCode = "404", description = "Branch not found")
            },
            security = {
                    @SecurityRequirement(name = "bearerAuth")
            }
    )
    @PreAuthorize("hasRole('store-admin')")
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/branch/{branchId}",
            produces = { "application/json", "application/xml" }
    )
    default ResponseEntity<BranchResponseDto> getBranchById(
            @Parameter(name = "branchId", description = "ID of Branch to return", required = true) @PathVariable("branchId") Long branchId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"branchId\" : 10, \"photoUrl\" : \"photoUrl\", \"address\" : { \"zip\" : \"94301\", \"country\" : \"Canada\", \"addresLine1\" : \"437 Lytton\", \"addresLine2\" : \"437 Lytton\", \"city\" : \"Palo Alto\", \"state\" : \"CA\", \"addressId\" : 10 }, \"branchName\" : \"Branch Toronto\", \"store\" : { \"photoUrl\" : \"photoUrl\", \"address\" : { \"zip\" : \"94301\", \"country\" : \"Canada\", \"addresLine1\" : \"437 Lytton\", \"addresLine2\" : \"437 Lytton\", \"city\" : \"Palo Alto\", \"state\" : \"CA\", \"addressId\" : 10 }, \"storeName\" : \"Auto Range, MagCity\", \"storeId\" : 10, \"status\" : \"ACTIVE\" }, \"status\" : \"ACTIVE\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/xml"))) {
                    String exampleString = "<BranchResponseDto> <branchId>10</branchId> <branchName>Branch Toronto</branchName> <photoUrl>aeiou</photoUrl> <status>aeiou</status> </BranchResponseDto>";
                    ApiUtil.setExampleResponse(request, "application/xml", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /branch : Update an existing Branch
     * Update an existing Branch by Id
     *
     * @param branchDto Update an existent Branch in the app (required)
     * @return Successful operation (status code 200)
     *         or Invalid ID supplied (status code 400)
     *         or Branch not found (status code 404)
     *         or Validation exception (status code 405)
     */
    @Operation(
            operationId = "updateBranch",
            summary = "Update an existing Branch",
            tags = { "branch" },
            responses = {
                    @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = BranchResponseDto.class)),
                            @Content(mediaType = "application/xml", schema = @Schema(implementation = BranchResponseDto.class))
                    }),
                    @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
                    @ApiResponse(responseCode = "404", description = "Branch not found"),
                    @ApiResponse(responseCode = "405", description = "Validation exception")
            },
            security = {
                    @SecurityRequirement(name = "bearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/branch",
            produces = { "application/json", "application/xml" },
            consumes = { "application/json", "application/xml", "application/x-www-form-urlencoded" }
    )
    default ResponseEntity<BranchResponseDto> updateBranch(
            @Parameter(name = "BranchDto", description = "Update an existent Branch in the app", required = true) @Valid @RequestBody BranchDto branchDto
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"branchId\" : 10, \"photoUrl\" : \"photoUrl\", \"address\" : { \"zip\" : \"94301\", \"country\" : \"Canada\", \"addresLine1\" : \"437 Lytton\", \"addresLine2\" : \"437 Lytton\", \"city\" : \"Palo Alto\", \"state\" : \"CA\", \"addressId\" : 10 }, \"branchName\" : \"Branch Toronto\", \"store\" : { \"photoUrl\" : \"photoUrl\", \"address\" : { \"zip\" : \"94301\", \"country\" : \"Canada\", \"addresLine1\" : \"437 Lytton\", \"addresLine2\" : \"437 Lytton\", \"city\" : \"Palo Alto\", \"state\" : \"CA\", \"addressId\" : 10 }, \"storeName\" : \"Auto Range, MagCity\", \"storeId\" : 10, \"status\" : \"ACTIVE\" }, \"status\" : \"ACTIVE\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/xml"))) {
                    String exampleString = "<BranchResponseDto> <branchId>10</branchId> <branchName>Branch Toronto</branchName> <photoUrl>aeiou</photoUrl> <status>aeiou</status> </BranchResponseDto>";
                    ApiUtil.setExampleResponse(request, "application/xml", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /branch/{branchId} : Updates a Branch in the app with form data
     *
     *
     * @param branchId ID of Branch to return (required)
     * @param storeId Store ID of Branch that needs to be updated (required)
     * @param branchName Name of Branch that needs to be updated (optional)
     * @param addressLine1 Address Line1 of Branch that needs to be updated (optional)
     * @param addressLine2 Address Line2 of Branch that needs to be updated (optional)
     * @param city City of Branch that needs to be updated (optional)
     * @param state State of Branch that needs to be updated (optional)
     * @param zipCode Zip Code of Branch that needs to be updated (optional)
     * @param country Country of Branch that needs to be updated (optional)
     * @param status Status of Branch that needs to be updated (optional)
     * @return Invalid input (status code 405)
     */
    @Operation(
            operationId = "updateBranchWithForm",
            summary = "Updates a Branch in the app with form data",
            tags = { "branch" },
            responses = {
                    @ApiResponse(responseCode = "405", description = "Invalid input")
            },
            security = {
                    @SecurityRequirement(name = "bearerAuth")
            }
    )
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/branch/{branchId}"
    )
    default ResponseEntity<Void> updateBranchWithForm(
            @Parameter(name = "branchId", description = "ID of Branch to return", required = true) @PathVariable("branchId") Long branchId,
            @NotNull @Parameter(name = "store_id", description = "Store ID of Branch that needs to be updated", required = true) @Valid @RequestParam(value = "store_id", required = true) Long storeId,
            @Parameter(name = "branchName", description = "Name of Branch that needs to be updated") @Valid @RequestParam(value = "branchName", required = false) String branchName,
            @Parameter(name = "addressLine1", description = "Address Line1 of Branch that needs to be updated") @Valid @RequestParam(value = "addressLine1", required = false) String addressLine1,
            @Parameter(name = "addressLine2", description = "Address Line2 of Branch that needs to be updated") @Valid @RequestParam(value = "addressLine2", required = false) String addressLine2,
            @Parameter(name = "city", description = "City of Branch that needs to be updated") @Valid @RequestParam(value = "city", required = false) String city,
            @Parameter(name = "state", description = "State of Branch that needs to be updated") @Valid @RequestParam(value = "state", required = false) String state,
            @Parameter(name = "zipCode", description = "Zip Code of Branch that needs to be updated") @Valid @RequestParam(value = "zipCode", required = false) Long zipCode,
            @Parameter(name = "country", description = "Country of Branch that needs to be updated") @Valid @RequestParam(value = "country", required = false) String country,
            @Parameter(name = "status", description = "Status of Branch that needs to be updated") @Valid @RequestParam(value = "status", required = false) String status
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
